package com.onlytanner.test.init;

import com.onlytanner.test.items.ItemAluminumIngot;
import com.onlytanner.test.items.ItemAluminumNugget;
import com.onlytanner.test.items.ItemBrassIngot;
import com.onlytanner.test.items.ItemBrassNugget;
import com.onlytanner.test.items.ItemBronzeIngot;
import com.onlytanner.test.items.ItemBronzeNugget;
import com.onlytanner.test.items.ItemChromiumIngot;
import com.onlytanner.test.items.ItemChromiumNugget;
import com.onlytanner.test.items.ItemCoalCoke;
import com.onlytanner.test.items.ItemCopperIngot;
import com.onlytanner.test.items.ItemCopperNugget;
import com.onlytanner.test.items.ItemCrushedBauxiteOre;
import com.onlytanner.test.items.ItemCrushedCassiteriteOre;
import com.onlytanner.test.items.ItemCrushedChromiteOre;
import com.onlytanner.test.items.ItemCrushedCupriteOre;
import com.onlytanner.test.items.ItemCrushedGarnieriteOre;
import com.onlytanner.test.items.ItemCrushedGoldOre;
import com.onlytanner.test.items.ItemCrushedIronOre;
import com.onlytanner.test.items.ItemCrushedRutileOre;
import com.onlytanner.test.items.ItemCrushedSphaleriteOre;
import com.onlytanner.test.items.ItemInvarIngot;
import com.onlytanner.test.items.ItemInvarNugget;
import com.onlytanner.test.items.ItemIronNugget;
import com.onlytanner.test.items.ItemNichromeIngot;
import com.onlytanner.test.items.ItemNichromeNugget;
import com.onlytanner.test.items.ItemNickelIngot;
import com.onlytanner.test.items.ItemNickelNugget;
import com.onlytanner.test.items.ItemNitinolIngot;
import com.onlytanner.test.items.ItemNitinolNugget;
import com.onlytanner.test.items.ItemRefractoryBrick;
import com.onlytanner.test.items.ItemRefractoryComposite;
import com.onlytanner.test.items.ItemSteelIngot;
import com.onlytanner.test.items.ItemSteelNugget;
import com.onlytanner.test.items.ItemTinIngot;
import com.onlytanner.test.items.ItemTinNugget;
import com.onlytanner.test.items.ItemTitaniumIngot;
import com.onlytanner.test.items.ItemTitaniumNugget;
import com.onlytanner.test.items.ItemZincIngot;
import com.onlytanner.test.items.ItemZincNugget;
import com.onlytanner.test.items.tools.ItemAluminumAxe;
import com.onlytanner.test.items.tools.ItemAluminumHoe;
import com.onlytanner.test.items.tools.ItemAluminumPickaxe;
import com.onlytanner.test.items.tools.ItemAluminumShovel;
import com.onlytanner.test.items.tools.ItemAluminumSword;
import com.onlytanner.test.items.tools.ItemBrassAxe;
import com.onlytanner.test.items.tools.ItemBrassHoe;
import com.onlytanner.test.items.tools.ItemBrassPickaxe;
import com.onlytanner.test.items.tools.ItemBrassShovel;
import com.onlytanner.test.items.tools.ItemBrassSword;
import com.onlytanner.test.items.tools.ItemBronzeAxe;
import com.onlytanner.test.items.tools.ItemBronzeHoe;
import com.onlytanner.test.items.tools.ItemBronzePickaxe;
import com.onlytanner.test.items.tools.ItemBronzeShovel;
import com.onlytanner.test.items.tools.ItemBronzeSword;
import com.onlytanner.test.items.tools.ItemChromiumAxe;
import com.onlytanner.test.items.tools.ItemChromiumHoe;
import com.onlytanner.test.items.tools.ItemChromiumPickaxe;
import com.onlytanner.test.items.tools.ItemChromiumShovel;
import com.onlytanner.test.items.tools.ItemChromiumSword;
import com.onlytanner.test.items.tools.ItemCopperAxe;
import com.onlytanner.test.items.tools.ItemCopperHoe;
import com.onlytanner.test.items.tools.ItemCopperPickaxe;
import com.onlytanner.test.items.tools.ItemCopperShovel;
import com.onlytanner.test.items.tools.ItemCopperSword;
import com.onlytanner.test.items.tools.ItemInvarAxe;
import com.onlytanner.test.items.tools.ItemInvarHoe;
import com.onlytanner.test.items.tools.ItemInvarPickaxe;
import com.onlytanner.test.items.tools.ItemInvarShovel;
import com.onlytanner.test.items.tools.ItemInvarSword;
import com.onlytanner.test.items.tools.ItemNichromeAxe;
import com.onlytanner.test.items.tools.ItemNichromeHoe;
import com.onlytanner.test.items.tools.ItemNichromePickaxe;
import com.onlytanner.test.items.tools.ItemNichromeShovel;
import com.onlytanner.test.items.tools.ItemNichromeSword;
import com.onlytanner.test.items.tools.ItemNickelAxe;
import com.onlytanner.test.items.tools.ItemNickelHoe;
import com.onlytanner.test.items.tools.ItemNickelPickaxe;
import com.onlytanner.test.items.tools.ItemNickelShovel;
import com.onlytanner.test.items.tools.ItemNickelSword;
import com.onlytanner.test.items.tools.ItemNitinolAxe;
import com.onlytanner.test.items.tools.ItemNitinolHoe;
import com.onlytanner.test.items.tools.ItemNitinolPickaxe;
import com.onlytanner.test.items.tools.ItemNitinolShovel;
import com.onlytanner.test.items.tools.ItemNitinolSword;
import com.onlytanner.test.items.tools.ItemSteelAxe;
import com.onlytanner.test.items.tools.ItemSteelHoe;
import com.onlytanner.test.items.tools.ItemSteelPickaxe;
import com.onlytanner.test.items.tools.ItemSteelShovel;
import com.onlytanner.test.items.tools.ItemSteelSword;
import com.onlytanner.test.items.tools.ItemTinAxe;
import com.onlytanner.test.items.tools.ItemTinHoe;
import com.onlytanner.test.items.tools.ItemTinPickaxe;
import com.onlytanner.test.items.tools.ItemTinShovel;
import com.onlytanner.test.items.tools.ItemTinSword;
import com.onlytanner.test.items.tools.ItemTitaniumAxe;
import com.onlytanner.test.items.tools.ItemTitaniumHoe;
import com.onlytanner.test.items.tools.ItemTitaniumPickaxe;
import com.onlytanner.test.items.tools.ItemTitaniumShovel;
import com.onlytanner.test.items.tools.ItemTitaniumSword;
import com.onlytanner.test.items.tools.ItemZincAxe;
import com.onlytanner.test.items.tools.ItemZincHoe;
import com.onlytanner.test.items.tools.ItemZincPickaxe;
import com.onlytanner.test.items.tools.ItemZincShovel;
import com.onlytanner.test.items.tools.ItemZincSword;

import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemAxe;
import net.minecraft.item.ItemHoe;
import net.minecraft.item.ItemPickaxe;
import net.minecraft.item.ItemSpade;
import net.minecraft.item.ItemSword;
import net.minecraftforge.common.util.EnumHelper;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModItems {

    public static Item refractory_composite;
    public static Item refractory_brick;
    public static Item coal_coke;

    public static Item crushed_bauxite_ore;
    public static Item crushed_cassiterite_ore;
    public static Item crushed_chromite_ore;
    public static Item crushed_cuprite_ore;
    public static Item crushed_garnierite_ore;
    public static Item crushed_gold_ore;
    public static Item crushed_iron_ore;
    public static Item crushed_rutile_ore;
    public static Item crushed_sphalerite_ore;
    public static Item crushed_wolframite_ore;

    public static Item aluminum_ingot;
    public static Item brass_ingot;
    public static Item bronze_ingot;
    public static Item chromium_ingot;
    public static Item copper_ingot;
    public static Item invar_ingot;
    public static Item nichrome_ingot;
    public static Item nickel_ingot;
    public static Item nitinol_ingot;
    public static Item steel_ingot;
    public static Item tin_ingot;
    public static Item titanium_ingot;
    public static Item zinc_ingot;

    public static Item aluminum_nugget;
    public static Item brass_nugget;
    public static Item bronze_nugget;
    public static Item chromium_nugget;
    public static Item copper_nugget;
    public static Item invar_nugget;
    public static Item iron_nugget;
    public static Item nichrome_nugget;
    public static Item nickel_nugget;
    public static Item nitinol_nugget;
    public static Item steel_nugget;
    public static Item tin_nugget;
    public static Item titanium_nugget;
    public static Item zinc_nugget;

    public static ItemPickaxe aluminum_pickaxe;
    public static ItemPickaxe brass_pickaxe;
    public static ItemPickaxe bronze_pickaxe;
    public static ItemPickaxe chromium_pickaxe;
    public static ItemPickaxe copper_pickaxe;
    public static ItemPickaxe invar_pickaxe;
    public static ItemPickaxe nichrome_pickaxe;
    public static ItemPickaxe nickel_pickaxe;
    public static ItemPickaxe nitinol_pickaxe;
    public static ItemPickaxe steel_pickaxe;
    public static ItemPickaxe tin_pickaxe;
    public static ItemPickaxe titanium_pickaxe;
    public static ItemPickaxe zinc_pickaxe;

    public static ItemSword aluminum_sword;
    public static ItemSword brass_sword;
    public static ItemSword bronze_sword;
    public static ItemSword chromium_sword;
    public static ItemSword copper_sword;
    public static ItemSword invar_sword;
    public static ItemSword nichrome_sword;
    public static ItemSword nickel_sword;
    public static ItemSword nitinol_sword;
    public static ItemSword steel_sword;
    public static ItemSword tin_sword;
    public static ItemSword titanium_sword;
    public static ItemSword zinc_sword;

    public static ItemSpade aluminum_shovel;
    public static ItemSpade brass_shovel;
    public static ItemSpade bronze_shovel;
    public static ItemSpade chromium_shovel;
    public static ItemSpade copper_shovel;
    public static ItemSpade invar_shovel;
    public static ItemSpade nichrome_shovel;
    public static ItemSpade nickel_shovel;
    public static ItemSpade nitinol_shovel;
    public static ItemSpade steel_shovel;
    public static ItemSpade tin_shovel;
    public static ItemSpade titanium_shovel;
    public static ItemSpade zinc_shovel;

    public static ItemAxe aluminum_axe;
    public static ItemAxe brass_axe;
    public static ItemAxe bronze_axe;
    public static ItemAxe chromium_axe;
    public static ItemAxe copper_axe;
    public static ItemAxe invar_axe;
    public static ItemAxe nichrome_axe;
    public static ItemAxe nickel_axe;
    public static ItemAxe nitinol_axe;
    public static ItemAxe steel_axe;
    public static ItemAxe tin_axe;
    public static ItemAxe titanium_axe;
    public static ItemAxe zinc_axe;

    public static ItemHoe aluminum_hoe;
    public static ItemHoe brass_hoe;
    public static ItemHoe bronze_hoe;
    public static ItemHoe chromium_hoe;
    public static ItemHoe copper_hoe;
    public static ItemHoe invar_hoe;
    public static ItemHoe nichrome_hoe;
    public static ItemHoe nickel_hoe;
    public static ItemHoe nitinol_hoe;
    public static ItemHoe steel_hoe;
    public static ItemHoe tin_hoe;
    public static ItemHoe titanium_hoe;
    public static ItemHoe zinc_hoe;

    public static final ToolMaterial ALUMINUM = EnumHelper.addToolMaterial("ALUMINUM", 1, 300, 7.0F, 1.0F, 10);
    public static final ToolMaterial BRASS = EnumHelper.addToolMaterial("BRASS", 1, 300, 6.0F, 1.0F, 10);
    public static final ToolMaterial BRONZE = EnumHelper.addToolMaterial("BRONZE", 1, 400, 6.0F, 1.0F, 14);
    public static final ToolMaterial COPPER = EnumHelper.addToolMaterial("COPPER", 1, 220, 5.0F, 1.0F, 10);
    public static final ToolMaterial CHROMIUM = EnumHelper.addToolMaterial("CHROMIUM", 3, 32, 20.0F, 1.0F, 25);
    public static final ToolMaterial INVAR = EnumHelper.addToolMaterial("INVAR", 2, 400, 6.0F, 1.0F, 8);
    public static final ToolMaterial NICKEL = EnumHelper.addToolMaterial("NICKEL", 1, 220, 5.0F, 1.0F, 12);
    public static final ToolMaterial NICHROME = EnumHelper.addToolMaterial("NICHROME", 2, 800, 12.0F, 2.0F, 18);
    public static final ToolMaterial NITINOL = EnumHelper.addToolMaterial("NITINOL", 2, 1200, 8.0F, 2.0F, 15);
    public static final ToolMaterial STEEL = EnumHelper.addToolMaterial("STEEL", 2, 800, 9.0F, 2.0F, 17);
    public static final ToolMaterial TIN = EnumHelper.addToolMaterial("TIN", 1, 220, 5.0F, 1.0F, 10);
    public static final ToolMaterial TITANIUM = EnumHelper.addToolMaterial("TITANIUM", 2, 600, 7.0F, 2.0F, 16);
    public static final ToolMaterial ZINC = EnumHelper.addToolMaterial("ZINC", 1, 150, 5.0F, 1.0F, 12);

    public static void init() {
        crushed_bauxite_ore = new ItemCrushedBauxiteOre();
        crushed_cassiterite_ore = new ItemCrushedCassiteriteOre();
        crushed_chromite_ore = new ItemCrushedChromiteOre();
        crushed_cuprite_ore = new ItemCrushedCupriteOre();
        crushed_garnierite_ore = new ItemCrushedGarnieriteOre();
        crushed_gold_ore = new ItemCrushedGoldOre();
        crushed_iron_ore = new ItemCrushedIronOre();
        crushed_rutile_ore = new ItemCrushedRutileOre();
        crushed_sphalerite_ore = new ItemCrushedSphaleriteOre();

        aluminum_ingot = new ItemAluminumIngot();
        brass_ingot = new ItemBrassIngot();
        bronze_ingot = new ItemBronzeIngot();
        chromium_ingot = new ItemChromiumIngot();
        copper_ingot = new ItemCopperIngot();
        invar_ingot = new ItemInvarIngot();
        nichrome_ingot = new ItemNichromeIngot();
        nickel_ingot = new ItemNickelIngot();
        nitinol_ingot = new ItemNitinolIngot();
        steel_ingot = new ItemSteelIngot();
        tin_ingot = new ItemTinIngot();
        titanium_ingot = new ItemTitaniumIngot();
        zinc_ingot = new ItemZincIngot();

        aluminum_nugget = new ItemAluminumNugget();
        brass_nugget = new ItemBrassNugget();
        bronze_nugget = new ItemBronzeNugget();
        chromium_nugget = new ItemChromiumNugget();
        copper_nugget = new ItemCopperNugget();
        invar_nugget = new ItemInvarNugget();
        iron_nugget = new ItemIronNugget();
        nichrome_nugget = new ItemNichromeNugget();
        nickel_nugget = new ItemNickelNugget();
        nitinol_nugget = new ItemNitinolNugget();
        steel_nugget = new ItemSteelNugget();
        tin_nugget = new ItemTinNugget();
        titanium_nugget = new ItemTitaniumNugget();
        zinc_nugget = new ItemZincNugget();

        aluminum_pickaxe = new ItemAluminumPickaxe();
        brass_pickaxe = new ItemBrassPickaxe();
        bronze_pickaxe = new ItemBronzePickaxe();
        chromium_pickaxe = new ItemChromiumPickaxe();
        copper_pickaxe = new ItemCopperPickaxe();
        invar_pickaxe = new ItemInvarPickaxe();
        nichrome_pickaxe = new ItemNichromePickaxe();
        nickel_pickaxe = new ItemNickelPickaxe();
        nitinol_pickaxe = new ItemNitinolPickaxe();
        steel_pickaxe = new ItemSteelPickaxe();
        tin_pickaxe = new ItemTinPickaxe();
        titanium_pickaxe = new ItemTitaniumPickaxe();
        zinc_pickaxe = new ItemZincPickaxe();

        aluminum_sword = new ItemAluminumSword();
        brass_sword = new ItemBrassSword();
        bronze_sword = new ItemBronzeSword();
        chromium_sword = new ItemChromiumSword();
        copper_sword = new ItemCopperSword();
        invar_sword = new ItemInvarSword();
        nichrome_sword = new ItemNichromeSword();
        nickel_sword = new ItemNickelSword();
        nitinol_sword = new ItemNitinolSword();
        steel_sword = new ItemSteelSword();
        tin_sword = new ItemTinSword();
        titanium_sword = new ItemTitaniumSword();
        zinc_sword = new ItemZincSword();

        aluminum_shovel = new ItemAluminumShovel();
        brass_shovel = new ItemBrassShovel();
        bronze_shovel = new ItemBronzeShovel();
        chromium_shovel = new ItemChromiumShovel();
        copper_shovel = new ItemCopperShovel();
        invar_shovel = new ItemInvarShovel();
        nichrome_shovel = new ItemNichromeShovel();
        nickel_shovel = new ItemNickelShovel();
        nitinol_shovel = new ItemNitinolShovel();
        steel_shovel = new ItemSteelShovel();
        tin_shovel = new ItemTinShovel();
        titanium_shovel = new ItemTitaniumShovel();
        zinc_shovel = new ItemZincShovel();

        aluminum_axe = new ItemAluminumAxe();
        brass_axe = new ItemBrassAxe();
        bronze_axe = new ItemBronzeAxe();
        chromium_axe = new ItemChromiumAxe();
        copper_axe = new ItemCopperAxe();
        invar_axe = new ItemInvarAxe();
        nichrome_axe = new ItemNichromeAxe();
        nickel_axe = new ItemNickelAxe();
        nitinol_axe = new ItemNitinolAxe();
        steel_axe = new ItemSteelAxe();
        tin_axe = new ItemTinAxe();
        titanium_axe = new ItemTitaniumAxe();
        zinc_axe = new ItemZincAxe();

        aluminum_hoe = new ItemAluminumHoe();
        brass_hoe = new ItemBrassHoe();
        bronze_hoe = new ItemBronzeHoe();
        chromium_hoe = new ItemChromiumHoe();
        copper_hoe = new ItemCopperHoe();
        invar_hoe = new ItemInvarHoe();
        nichrome_hoe = new ItemNichromeHoe();
        nickel_hoe = new ItemNickelHoe();
        nitinol_hoe = new ItemNitinolHoe();
        steel_hoe = new ItemSteelHoe();
        tin_hoe = new ItemTinHoe();
        titanium_hoe = new ItemTitaniumHoe();
        zinc_hoe = new ItemZincHoe();

        refractory_composite = new ItemRefractoryComposite();
        refractory_brick = new ItemRefractoryBrick();
        coal_coke = new ItemCoalCoke();
    }

    public static void register() {
        GameRegistry.register(crushed_bauxite_ore);
        GameRegistry.register(crushed_cassiterite_ore);
        GameRegistry.register(crushed_chromite_ore);
        GameRegistry.register(crushed_cuprite_ore);
        GameRegistry.register(crushed_garnierite_ore);
        GameRegistry.register(crushed_gold_ore);
        GameRegistry.register(crushed_iron_ore);
        GameRegistry.register(crushed_rutile_ore);
        GameRegistry.register(crushed_sphalerite_ore);

        GameRegistry.register(aluminum_ingot);
        GameRegistry.register(brass_ingot);
        GameRegistry.register(bronze_ingot);
        GameRegistry.register(chromium_ingot);
        GameRegistry.register(copper_ingot);
        GameRegistry.register(invar_ingot);
        GameRegistry.register(nichrome_ingot);
        GameRegistry.register(nickel_ingot);
        GameRegistry.register(nitinol_ingot);
        GameRegistry.register(steel_ingot);
        GameRegistry.register(tin_ingot);
        GameRegistry.register(titanium_ingot);
        GameRegistry.register(zinc_ingot);

        GameRegistry.register(aluminum_nugget);
        GameRegistry.register(brass_nugget);
        GameRegistry.register(bronze_nugget);
        GameRegistry.register(chromium_nugget);
        GameRegistry.register(copper_nugget);
        GameRegistry.register(invar_nugget);
        GameRegistry.register(iron_nugget);
        GameRegistry.register(nichrome_nugget);
        GameRegistry.register(nickel_nugget);
        GameRegistry.register(nitinol_nugget);
        GameRegistry.register(steel_nugget);
        GameRegistry.register(tin_nugget);
        GameRegistry.register(titanium_nugget);
        GameRegistry.register(zinc_nugget);
        //pick
        GameRegistry.register(aluminum_pickaxe);
        GameRegistry.register(brass_pickaxe);
        GameRegistry.register(bronze_pickaxe);
        GameRegistry.register(chromium_pickaxe);
        GameRegistry.register(copper_pickaxe);
        GameRegistry.register(invar_pickaxe);
        GameRegistry.register(nichrome_pickaxe);
        GameRegistry.register(nickel_pickaxe);
        GameRegistry.register(nitinol_pickaxe);
        GameRegistry.register(steel_pickaxe);
        GameRegistry.register(tin_pickaxe);
        GameRegistry.register(titanium_pickaxe);
        GameRegistry.register(zinc_pickaxe);
        //sword
        GameRegistry.register(aluminum_sword);
        GameRegistry.register(brass_sword);
        GameRegistry.register(bronze_sword);
        GameRegistry.register(chromium_sword);
        GameRegistry.register(copper_sword);
        GameRegistry.register(invar_sword);
        GameRegistry.register(nichrome_sword);
        GameRegistry.register(nickel_sword);
        GameRegistry.register(nitinol_sword);
        GameRegistry.register(steel_sword);
        GameRegistry.register(tin_sword);
        GameRegistry.register(titanium_sword);
        GameRegistry.register(zinc_sword);
        //shovel
        GameRegistry.register(aluminum_shovel);
        GameRegistry.register(brass_shovel);
        GameRegistry.register(bronze_shovel);
        GameRegistry.register(chromium_shovel);
        GameRegistry.register(copper_shovel);
        GameRegistry.register(invar_shovel);
        GameRegistry.register(nichrome_shovel);
        GameRegistry.register(nickel_shovel);
        GameRegistry.register(nitinol_shovel);
        GameRegistry.register(steel_shovel);
        GameRegistry.register(tin_shovel);
        GameRegistry.register(titanium_shovel);
        GameRegistry.register(zinc_shovel);
        //axe
        GameRegistry.register(aluminum_axe);
        GameRegistry.register(brass_axe);
        GameRegistry.register(bronze_axe);
        GameRegistry.register(chromium_axe);
        GameRegistry.register(copper_axe);
        GameRegistry.register(invar_axe);
        GameRegistry.register(nichrome_axe);
        GameRegistry.register(nickel_axe);
        GameRegistry.register(nitinol_axe);
        GameRegistry.register(steel_axe);
        GameRegistry.register(tin_axe);
        GameRegistry.register(titanium_axe);
        GameRegistry.register(zinc_axe);
        //hoe
        GameRegistry.register(aluminum_hoe);
        GameRegistry.register(brass_hoe);
        GameRegistry.register(bronze_hoe);
        GameRegistry.register(chromium_hoe);
        GameRegistry.register(copper_hoe);
        GameRegistry.register(invar_hoe);
        GameRegistry.register(nichrome_hoe);
        GameRegistry.register(nickel_hoe);
        GameRegistry.register(nitinol_hoe);
        GameRegistry.register(steel_hoe);
        GameRegistry.register(tin_hoe);
        GameRegistry.register(titanium_hoe);
        GameRegistry.register(zinc_hoe);

        GameRegistry.register(refractory_composite);
        GameRegistry.register(refractory_brick);
        GameRegistry.register(coal_coke);
    }

    public static void registerRenders() {
        registerRender(crushed_bauxite_ore);
        registerRender(crushed_cassiterite_ore);
        registerRender(crushed_chromite_ore);
        registerRender(crushed_cuprite_ore);
        registerRender(crushed_garnierite_ore);
        registerRender(crushed_gold_ore);
        registerRender(crushed_iron_ore);
        registerRender(crushed_rutile_ore);
        registerRender(crushed_sphalerite_ore);

        registerRender(aluminum_ingot);
        registerRender(brass_ingot);
        registerRender(bronze_ingot);
        registerRender(chromium_ingot);
        registerRender(copper_ingot);
        registerRender(invar_ingot);
        registerRender(nichrome_ingot);
        registerRender(nickel_ingot);
        registerRender(nitinol_ingot);
        registerRender(steel_ingot);
        registerRender(tin_ingot);
        registerRender(titanium_ingot);
        registerRender(zinc_ingot);

        registerRender(aluminum_nugget);
        registerRender(brass_nugget);
        registerRender(bronze_nugget);
        registerRender(chromium_nugget);
        registerRender(copper_nugget);
        registerRender(invar_nugget);
        registerRender(iron_nugget);
        registerRender(nichrome_nugget);
        registerRender(nickel_nugget);
        registerRender(nitinol_nugget);
        registerRender(steel_nugget);
        registerRender(tin_nugget);
        registerRender(titanium_nugget);
        registerRender(zinc_nugget);
        //pick
        registerRender(aluminum_pickaxe);
        registerRender(brass_pickaxe);
        registerRender(bronze_pickaxe);
        registerRender(chromium_pickaxe);
        registerRender(copper_pickaxe);
        registerRender(invar_pickaxe);
        registerRender(nichrome_pickaxe);
        registerRender(nickel_pickaxe);
        registerRender(nitinol_pickaxe);
        registerRender(steel_pickaxe);
        registerRender(tin_pickaxe);
        registerRender(titanium_pickaxe);
        registerRender(zinc_pickaxe);
        //sword
        registerRender(aluminum_sword);
        registerRender(brass_sword);
        registerRender(bronze_sword);
        registerRender(chromium_sword);
        registerRender(copper_sword);
        registerRender(invar_sword);
        registerRender(nichrome_sword);
        registerRender(nickel_sword);
        registerRender(nitinol_sword);
        registerRender(steel_sword);
        registerRender(tin_sword);
        registerRender(titanium_sword);
        registerRender(zinc_sword);
        //shovel
        registerRender(aluminum_shovel);
        registerRender(brass_shovel);
        registerRender(bronze_shovel);
        registerRender(chromium_shovel);
        registerRender(copper_shovel);
        registerRender(invar_shovel);
        registerRender(nichrome_shovel);
        registerRender(nickel_shovel);
        registerRender(nitinol_shovel);
        registerRender(steel_shovel);
        registerRender(tin_shovel);
        registerRender(titanium_shovel);
        registerRender(zinc_shovel);
        //axe
        registerRender(aluminum_axe);
        registerRender(brass_axe);
        registerRender(bronze_axe);
        registerRender(chromium_axe);
        registerRender(copper_axe);
        registerRender(invar_axe);
        registerRender(nichrome_axe);
        registerRender(nickel_axe);
        registerRender(nitinol_axe);
        registerRender(steel_axe);
        registerRender(tin_axe);
        registerRender(titanium_axe);
        registerRender(zinc_axe);
        //hoe
        registerRender(aluminum_hoe);
        registerRender(brass_hoe);
        registerRender(bronze_hoe);
        registerRender(chromium_hoe);
        registerRender(copper_hoe);
        registerRender(invar_hoe);
        registerRender(nichrome_hoe);
        registerRender(nickel_hoe);
        registerRender(nitinol_hoe);
        registerRender(steel_hoe);
        registerRender(tin_hoe);
        registerRender(titanium_hoe);
        registerRender(zinc_hoe);

        registerRender(refractory_composite);
        registerRender(refractory_brick);
        registerRender(coal_coke);
    }

    private static void registerRender(Item item) {
        Minecraft.getMinecraft().getRenderItem().getItemModelMesher().register(item, 0, new ModelResourceLocation(item.getRegistryName(), "inventory"));
    }
}
