package com.onlytanner.industrialmetallurgy.init;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class ModCrafting
{
    public static void register()
    {
        GameRegistry.addShapedRecipe(new ItemStack(Items.IRON_INGOT), "XXX", "XXX", "XXX", 'X', ModItems.iron_nugget);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.iron_nugget, 9), Items.IRON_INGOT);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.refractory_composite), "SCS", "CBC", "SCS", 'S', Blocks.SAND, 'C', Items.CLAY_BALL, 'B', new ItemStack(Items.DYE, 1, 15));
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.refractory_composite), "CSC", "SBS", "CSC", 'S', Blocks.SAND, 'C', Items.CLAY_BALL, 'B', new ItemStack(Items.DYE, 1, 15));
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.memory_wire, 8), "   ", "NNN", "   ", 'N', ModItems.nitinol_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.magnet_wire, 8), "   ", "CCC", "   ", 'C', ModItems.copper_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.resistance_wire, 8), "   ", "KNK", "   ", 'N', ModItems.nichrome_ingot, 'K', ModItems.kanthal_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.lead_sulfate_plate), "BB ", "BB ", "   ", 'B', ModItems.lead_sulfate);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.lead_sulfate_plate), " BB", " BB", "   ", 'B', ModItems.lead_sulfate);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.lead_sulfate_plate), "   ", "BB ", "BB ", 'B', ModItems.lead_sulfate);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.lead_sulfate_plate), "   ", " BB", " BB", 'B', ModItems.lead_sulfate);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.conducting_element), "MCM", "RGR", "MCM", 'M', ModItems.memory_wire, 'C', ModItems.copper_ingot, 'R', Items.REDSTONE, 'G', Items.GOLD_INGOT);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.conducting_element), "MCM", "RGR", "MCM", 'M', ModItems.memory_wire, 'C', Items.REDSTONE, 'R', ModItems.copper_ingot, 'G', Items.GOLD_INGOT);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.heating_element), "RRR", "RCR", "RRR", 'R', ModItems.resistance_wire, 'C', ModItems.conducting_element);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.field_coil), "MMM", "MSM", "MMM", 'M', ModItems.magnet_wire, 'S', ModItems.steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.stator), "FIF", "I I", "FIF", 'F', ModItems.invar_ingot, 'I', ModItems.field_coil);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.rotor), "AFA", "FSF", "AFA", 'S', ModItems.steel_ingot, 'F', ModItems.field_coil, 'A', ModItems.aluminum_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.battery_cell), "PSP", "LCL", "PSP", 'C', ModItems.conducting_element, 'P', ModItems.hdpe_sheet, 'S', ModItems.sulfuric_acid_bottle, 'L', ModItems.lead_sulfate_plate);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.battery_cell), "PLP", "SCS", "PLP", 'C', ModItems.conducting_element, 'P', ModItems.hdpe_sheet, 'S', ModItems.sulfuric_acid_bottle, 'L', ModItems.lead_sulfate_plate);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.battery_bank), "MBM", "BBB", "MBM", 'B', ModItems.battery_cell, 'M', ModItems.magnet_wire);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.electric_motor), " R ", "VSV", " C ", 'S', ModItems.stator, 'R', ModItems.rotor, 'C', ModItems.conducting_element, 'V', Items.REDSTONE);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.electric_motor), "V R", " S ", "C V", 'S', ModItems.stator, 'R', ModItems.rotor, 'C', ModItems.conducting_element, 'V', Items.REDSTONE);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.induction_core), "RHR", "CHC", "RHR", 'R', ModItems.copper_ingot, 'H', ModItems.heating_element, 'C', ModItems.conducting_element);
        GameRegistry.addSmelting(ModItems.refractory_composite, new ItemStack(ModItems.refractory_brick), 0.35F);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.refractory_bricks), "BB ", "BB ", "   ", 'B', ModItems.refractory_brick);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.refractory_bricks), " BB", " BB", "   ", 'B', ModItems.refractory_brick);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.refractory_bricks), "   ", "BB ", "BB ", 'B', ModItems.refractory_brick);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.refractory_bricks), "   ", " BB", " BB", 'B', ModItems.refractory_brick);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.iron_forge_core), "IBI", "B B", "IBI", 'I', Blocks.IRON_BLOCK, 'B', ModBlocks.refractory_bricks);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.cobalt_forge_core), "IBI", "B B", "IBI", 'I', ModBlocks.cobalt_steel_block, 'B', ModBlocks.refractory_bricks);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.tungsten_forge_core), "IBI", "BCB", "IBI", 'I', ModBlocks.tungsten_steel_block, 'B', ModBlocks.refractory_bricks, 'C', ModItems.induction_core);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.forge_tier1), "III", "ICI", "IFI", 'I', Items.IRON_INGOT, 'F', Blocks.FURNACE, 'C', ModBlocks.iron_forge_core);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.forge_tier2), "III", "ICI", "IFI", 'I', ModItems.cobalt_steel_ingot, 'F', ModBlocks.forge_tier1, 'C', ModBlocks.cobalt_forge_core);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.forge_tier3), "IBI", "ICI", "IFI", 'I', ModItems.tungsten_steel_ingot, 'F', ModBlocks.forge_tier2, 'C', ModBlocks.tungsten_forge_core, 'B', ModItems.battery_cell);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.crusher), "IBI", "OPO", "OOO", 'I', Blocks.IRON_BLOCK, 'B', Blocks.IRON_BARS, 'O', Blocks.OBSIDIAN, 'P', Items.DIAMOND_PICKAXE);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.coke_oven), "BBB", "B B", "BBB", 'B', ModBlocks.refractory_bricks);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.coal_generator), "BAB", "RER", "BRB", 'B', ModBlocks.bronze_block, 'R', ModBlocks.refractory_bricks, 'E', ModItems.electric_motor, 'A', ModItems.battery_bank);

        //GameRegistry.addShapelessRecipe(new ItemStack(ModItems.alloy7201_ingot, 9), ModBlocks.alloy7201_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.alloy7201_nugget, 9), ModItems.alloy7201_ingot);
        //GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.alloy7201_block), "XXX", "XXX", "XXX", 'X', ModItems.alloy7201_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_ingot), "XXX", "XXX", "XXX", 'X', ModItems.alloy7201_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_sword), "C  ", "C  ", "S  ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_sword), " C ", " C ", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_sword), "  C", "  C", "  S", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_pickaxe), "CCC", " S ", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_shovel), " C ", " S ", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_shovel), "  C", "  S", "  S", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_shovel), "C  ", "S  ", "S  ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_axe), " CC", " SC", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_axe), "CC ", "SC ", "S  ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_axe), "CC ", "CS ", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_axe), " CC", " CS", "  S", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_hoe), " CC", " S ", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_hoe), "CC ", "S  ", "S  ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_hoe), "CC ", " S ", " S ", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.alloy7201_hoe), " CC", "  S", "  S", 'C', ModItems.alloy7201_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.aluminum_ingot, 9), ModBlocks.aluminum_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.aluminum_nugget, 9), ModItems.aluminum_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.aluminum_block), "XXX", "XXX", "XXX", 'X', ModItems.aluminum_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_ingot), "XXX", "XXX", "XXX", 'X', ModItems.aluminum_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_sword), "C  ", "C  ", "S  ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_sword), " C ", " C ", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_sword), "  C", "  C", "  S", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_pickaxe), "CCC", " S ", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_shovel), " C ", " S ", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_shovel), "  C", "  S", "  S", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_shovel), "C  ", "S  ", "S  ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_axe), " CC", " SC", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_axe), "CC ", "SC ", "S  ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_axe), "CC ", "CS ", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_axe), " CC", " CS", "  S", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_hoe), " CC", " S ", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_hoe), "CC ", "S  ", "S  ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_hoe), "CC ", " S ", " S ", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.aluminum_hoe), " CC", "  S", "  S", 'C', ModItems.aluminum_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.brass_ingot, 9), ModBlocks.brass_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.brass_nugget, 9), ModItems.brass_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.brass_block), "XXX", "XXX", "XXX", 'X', ModItems.brass_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_ingot), "XXX", "XXX", "XXX", 'X', ModItems.brass_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_sword), "C  ", "C  ", "S  ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_sword), " C ", " C ", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_sword), "  C", "  C", "  S", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_pickaxe), "CCC", " S ", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_shovel), " C ", " S ", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_shovel), "  C", "  S", "  S", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_shovel), "C  ", "S  ", "S  ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_axe), " CC", " SC", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_axe), "CC ", "SC ", "S  ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_axe), "CC ", "CS ", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_axe), " CC", " CS", "  S", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_hoe), " CC", " S ", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_hoe), "CC ", "S  ", "S  ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_hoe), "CC ", " S ", " S ", 'C', ModItems.brass_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.brass_hoe), " CC", "  S", "  S", 'C', ModItems.brass_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.bronze_ingot, 9), ModBlocks.bronze_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.bronze_nugget, 9), ModItems.bronze_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.bronze_block), "XXX", "XXX", "XXX", 'X', ModItems.bronze_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_ingot), "XXX", "XXX", "XXX", 'X', ModItems.bronze_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_sword), "C  ", "C  ", "S  ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_sword), " C ", " C ", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_sword), "  C", "  C", "  S", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_pickaxe), "CCC", " S ", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_shovel), " C ", " S ", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_shovel), "  C", "  S", "  S", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_shovel), "C  ", "S  ", "S  ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_axe), " CC", " SC", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_axe), "CC ", "SC ", "S  ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_axe), "CC ", "CS ", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_axe), " CC", " CS", "  S", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_hoe), " CC", " S ", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_hoe), "CC ", "S  ", "S  ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_hoe), "CC ", " S ", " S ", 'C', ModItems.bronze_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.bronze_hoe), " CC", "  S", "  S", 'C', ModItems.bronze_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.chromium_ingot, 9), ModBlocks.chromium_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.chromium_nugget, 9), ModItems.chromium_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.chromium_block), "XXX", "XXX", "XXX", 'X', ModItems.chromium_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_ingot), "XXX", "XXX", "XXX", 'X', ModItems.chromium_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_sword), "C  ", "C  ", "S  ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_sword), " C ", " C ", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_sword), "  C", "  C", "  S", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_pickaxe), "CCC", " S ", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_shovel), " C ", " S ", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_shovel), "  C", "  S", "  S", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_shovel), "C  ", "S  ", "S  ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_axe), " CC", " SC", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_axe), "CC ", "SC ", "S  ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_axe), "CC ", "CS ", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_axe), " CC", " CS", "  S", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_hoe), " CC", " S ", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_hoe), "CC ", "S  ", "S  ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_hoe), "CC ", " S ", " S ", 'C', ModItems.chromium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.chromium_hoe), " CC", "  S", "  S", 'C', ModItems.chromium_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.cobalt_ingot, 9), ModBlocks.cobalt_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.cobalt_nugget, 9), ModItems.cobalt_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.cobalt_block), "XXX", "XXX", "XXX", 'X', ModItems.cobalt_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_ingot), "XXX", "XXX", "XXX", 'X', ModItems.cobalt_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_sword), "C  ", "C  ", "S  ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_sword), " C ", " C ", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_sword), "  C", "  C", "  S", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_pickaxe), "CCC", " S ", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_shovel), " C ", " S ", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_shovel), "  C", "  S", "  S", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_shovel), "C  ", "S  ", "S  ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_axe), " CC", " SC", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_axe), "CC ", "SC ", "S  ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_axe), "CC ", "CS ", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_axe), " CC", " CS", "  S", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_hoe), " CC", " S ", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_hoe), "CC ", "S  ", "S  ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_hoe), "CC ", " S ", " S ", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_hoe), " CC", "  S", "  S", 'C', ModItems.cobalt_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.cobalt_steel_ingot, 9), ModBlocks.cobalt_steel_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.cobalt_steel_nugget, 9), ModItems.cobalt_steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.cobalt_steel_block), "XXX", "XXX", "XXX", 'X', ModItems.cobalt_steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.cobalt_steel_ingot), "XXX", "XXX", "XXX", 'X', ModItems.cobalt_steel_nugget);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.copper_ingot, 9), ModBlocks.copper_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.copper_nugget, 9), ModItems.copper_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.copper_block), "XXX", "XXX", "XXX", 'X', ModItems.copper_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_ingot), "XXX", "XXX", "XXX", 'X', ModItems.copper_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_sword), "C  ", "C  ", "S  ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_sword), " C ", " C ", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_sword), "  C", "  C", "  S", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_pickaxe), "CCC", " S ", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_shovel), " C ", " S ", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_shovel), "  C", "  S", "  S", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_shovel), "C  ", "S  ", "S  ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_axe), " CC", " SC", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_axe), "CC ", "SC ", "S  ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_axe), "CC ", "CS ", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_axe), " CC", " CS", "  S", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_hoe), " CC", " S ", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_hoe), "CC ", "S  ", "S  ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_hoe), "CC ", " S ", " S ", 'C', ModItems.copper_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.copper_hoe), " CC", "  S", "  S", 'C', ModItems.copper_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.invar_ingot, 9), ModBlocks.invar_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.invar_nugget, 9), ModItems.invar_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.invar_block), "XXX", "XXX", "XXX", 'X', ModItems.invar_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_ingot), "XXX", "XXX", "XXX", 'X', ModItems.invar_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_sword), "C  ", "C  ", "S  ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_sword), " C ", " C ", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_sword), "  C", "  C", "  S", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_pickaxe), "CCC", " S ", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_shovel), " C ", " S ", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_shovel), "  C", "  S", "  S", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_shovel), "C  ", "S  ", "S  ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_axe), " CC", " SC", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_axe), "CC ", "SC ", "S  ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_axe), "CC ", "CS ", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_axe), " CC", " CS", "  S", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_hoe), " CC", " S ", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_hoe), "CC ", "S  ", "S  ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_hoe), "CC ", " S ", " S ", 'C', ModItems.invar_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.invar_hoe), " CC", "  S", "  S", 'C', ModItems.invar_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.nichrome_ingot, 9), ModBlocks.nichrome_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.nichrome_nugget, 9), ModItems.nichrome_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.nichrome_block), "XXX", "XXX", "XXX", 'X', ModItems.nichrome_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_ingot), "XXX", "XXX", "XXX", 'X', ModItems.nichrome_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_sword), "C  ", "C  ", "S  ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_sword), " C ", " C ", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_sword), "  C", "  C", "  S", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_pickaxe), "CCC", " S ", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_shovel), " C ", " S ", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_shovel), "  C", "  S", "  S", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_shovel), "C  ", "S  ", "S  ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_axe), " CC", " SC", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_axe), "CC ", "SC ", "S  ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_axe), "CC ", "CS ", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_axe), " CC", " CS", "  S", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_hoe), " CC", " S ", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_hoe), "CC ", "S  ", "S  ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_hoe), "CC ", " S ", " S ", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nichrome_hoe), " CC", "  S", "  S", 'C', ModItems.nichrome_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.nickel_ingot, 9), ModBlocks.nickel_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.nickel_nugget, 9), ModItems.nickel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.nickel_block), "XXX", "XXX", "XXX", 'X', ModItems.nickel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_ingot), "XXX", "XXX", "XXX", 'X', ModItems.nickel_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_sword), "C  ", "C  ", "S  ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_sword), " C ", " C ", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_sword), "  C", "  C", "  S", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_pickaxe), "CCC", " S ", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_shovel), " C ", " S ", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_shovel), "  C", "  S", "  S", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_shovel), "C  ", "S  ", "S  ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_axe), " CC", " SC", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_axe), "CC ", "SC ", "S  ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_axe), "CC ", "CS ", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_axe), " CC", " CS", "  S", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_hoe), " CC", " S ", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_hoe), "CC ", "S  ", "S  ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_hoe), "CC ", " S ", " S ", 'C', ModItems.nickel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nickel_hoe), " CC", "  S", "  S", 'C', ModItems.nickel_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.nitinol_ingot, 9), ModBlocks.nitinol_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.nitinol_nugget, 9), ModItems.nitinol_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.nitinol_block), "XXX", "XXX", "XXX", 'X', ModItems.nitinol_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_ingot), "XXX", "XXX", "XXX", 'X', ModItems.nitinol_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_sword), "C  ", "C  ", "S  ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_sword), " C ", " C ", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_sword), "  C", "  C", "  S", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_pickaxe), "CCC", " S ", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_shovel), " C ", " S ", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_shovel), "  C", "  S", "  S", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_shovel), "C  ", "S  ", "S  ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_axe), " CC", " SC", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_axe), "CC ", "SC ", "S  ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_axe), "CC ", "CS ", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_axe), " CC", " CS", "  S", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_hoe), " CC", " S ", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_hoe), "CC ", "S  ", "S  ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_hoe), "CC ", " S ", " S ", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.nitinol_hoe), " CC", "  S", "  S", 'C', ModItems.nitinol_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.steel_ingot, 9), ModBlocks.steel_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.steel_nugget, 9), ModItems.steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.steel_block), "XXX", "XXX", "XXX", 'X', ModItems.steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_ingot), "XXX", "XXX", "XXX", 'X', ModItems.steel_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_sword), "C  ", "C  ", "S  ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_sword), " C ", " C ", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_sword), "  C", "  C", "  S", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_pickaxe), "CCC", " S ", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_shovel), " C ", " S ", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_shovel), "  C", "  S", "  S", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_shovel), "C  ", "S  ", "S  ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_axe), " CC", " SC", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_axe), "CC ", "SC ", "S  ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_axe), "CC ", "CS ", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_axe), " CC", " CS", "  S", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_hoe), " CC", " S ", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_hoe), "CC ", "S  ", "S  ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_hoe), "CC ", " S ", " S ", 'C', ModItems.steel_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.steel_hoe), " CC", "  S", "  S", 'C', ModItems.steel_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.tin_ingot, 9), ModBlocks.tin_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.tin_nugget, 9), ModItems.tin_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.tin_block), "XXX", "XXX", "XXX", 'X', ModItems.tin_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_ingot), "XXX", "XXX", "XXX", 'X', ModItems.tin_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_sword), "C  ", "C  ", "S  ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_sword), " C ", " C ", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_sword), "  C", "  C", "  S", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_pickaxe), "CCC", " S ", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_shovel), " C ", " S ", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_shovel), "  C", "  S", "  S", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_shovel), "C  ", "S  ", "S  ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_axe), " CC", " SC", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_axe), "CC ", "SC ", "S  ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_axe), "CC ", "CS ", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_axe), " CC", " CS", "  S", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_hoe), " CC", " S ", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_hoe), "CC ", "S  ", "S  ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_hoe), "CC ", " S ", " S ", 'C', ModItems.tin_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tin_hoe), " CC", "  S", "  S", 'C', ModItems.tin_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.titanium_ingot, 9), ModBlocks.titanium_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.titanium_nugget, 9), ModItems.titanium_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.titanium_block), "XXX", "XXX", "XXX", 'X', ModItems.titanium_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_ingot), "XXX", "XXX", "XXX", 'X', ModItems.titanium_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_sword), "C  ", "C  ", "S  ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_sword), " C ", " C ", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_sword), "  C", "  C", "  S", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_pickaxe), "CCC", " S ", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_shovel), " C ", " S ", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_shovel), "  C", "  S", "  S", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_shovel), "C  ", "S  ", "S  ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_axe), " CC", " SC", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_axe), "CC ", "SC ", "S  ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_axe), "CC ", "CS ", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_axe), " CC", " CS", "  S", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_hoe), " CC", " S ", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_hoe), "CC ", "S  ", "S  ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_hoe), "CC ", " S ", " S ", 'C', ModItems.titanium_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.titanium_hoe), " CC", "  S", "  S", 'C', ModItems.titanium_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.tungsten_ingot, 9), ModBlocks.tungsten_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.tungsten_nugget, 9), ModItems.tungsten_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.tungsten_block), "XXX", "XXX", "XXX", 'X', ModItems.tungsten_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_ingot), "XXX", "XXX", "XXX", 'X', ModItems.tungsten_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_sword), "C  ", "C  ", "S  ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_sword), " C ", " C ", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_sword), "  C", "  C", "  S", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_pickaxe), "CCC", " S ", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_shovel), " C ", " S ", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_shovel), "  C", "  S", "  S", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_shovel), "C  ", "S  ", "S  ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_axe), " CC", " SC", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_axe), "CC ", "SC ", "S  ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_axe), "CC ", "CS ", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_axe), " CC", " CS", "  S", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_hoe), " CC", " S ", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_hoe), "CC ", "S  ", "S  ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_hoe), "CC ", " S ", " S ", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_hoe), " CC", "  S", "  S", 'C', ModItems.tungsten_ingot, 'S', Items.STICK);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.tungsten_steel_ingot, 9), ModBlocks.tungsten_steel_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.tungsten_steel_nugget, 9), ModItems.tungsten_steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.tungsten_steel_block), "XXX", "XXX", "XXX", 'X', ModItems.tungsten_steel_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.tungsten_steel_ingot), "XXX", "XXX", "XXX", 'X', ModItems.tungsten_steel_nugget);

        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.zinc_ingot, 9), ModBlocks.zinc_block);
        GameRegistry.addShapelessRecipe(new ItemStack(ModItems.zinc_nugget, 9), ModItems.zinc_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModBlocks.zinc_block), "XXX", "XXX", "XXX", 'X', ModItems.zinc_ingot);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_ingot), "XXX", "XXX", "XXX", 'X', ModItems.zinc_nugget);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_sword), "C  ", "C  ", "S  ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_sword), " C ", " C ", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_sword), "  C", "  C", "  S", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_pickaxe), "CCC", " S ", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_shovel), " C ", " S ", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_shovel), "  C", "  S", "  S", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_shovel), "C  ", "S  ", "S  ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_axe), " CC", " SC", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_axe), "CC ", "SC ", "S  ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_axe), "CC ", "CS ", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_axe), " CC", " CS", "  S", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_hoe), " CC", " S ", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_hoe), "CC ", "S  ", "S  ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_hoe), "CC ", " S ", " S ", 'C', ModItems.zinc_ingot, 'S', Items.STICK);
        GameRegistry.addShapedRecipe(new ItemStack(ModItems.zinc_hoe), " CC", "  S", "  S", 'C', ModItems.zinc_ingot, 'S', Items.STICK);

        GameRegistry.addSmelting(ModBlocks.bauxite_ore, new ItemStack(ModItems.aluminum_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.cassiterite_ore, new ItemStack(ModItems.tin_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.chromite_ore, new ItemStack(ModItems.chromium_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.cobaltite_ore, new ItemStack(ModItems.cobalt_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.cuprite_ore, new ItemStack(ModItems.copper_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.garnierite_ore, new ItemStack(ModItems.nickel_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.rutile_ore, new ItemStack(ModItems.titanium_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.sphalerite_ore, new ItemStack(ModItems.zinc_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModBlocks.wolframite_ore, new ItemStack(ModItems.tungsten_ingot), (float) 0.35);

        GameRegistry.addSmelting(ModItems.crushed_bauxite_ore, new ItemStack(ModItems.aluminum_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_cassiterite_ore, new ItemStack(ModItems.tin_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_chromite_ore, new ItemStack(ModItems.chromium_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_cobaltite_ore, new ItemStack(ModItems.cobalt_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_cuprite_ore, new ItemStack(ModItems.copper_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_garnierite_ore, new ItemStack(ModItems.nickel_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_gold_ore, new ItemStack(Items.GOLD_INGOT), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_iron_ore, new ItemStack(Items.IRON_INGOT), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_rutile_ore, new ItemStack(ModItems.titanium_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_sphalerite_ore, new ItemStack(ModItems.zinc_ingot), (float) 0.35);
        GameRegistry.addSmelting(ModItems.crushed_wolframite_ore, new ItemStack(ModItems.tungsten_ingot), (float) 0.35);
    }
}
